### ISSUE TITLE
socket connection error: not authorized

### ISSUE THREAD

**Issue by iw2lsi** [andrei-tatar/node-red-contrib-nora#111]
Hi all,

  am I the only one experiencing problems trying to connect to NORA?

most of the time it does my nora components are not able to connect to the server and when I try to reach the login page:

https://node-red-google-home.herokuapp.com/login

a simple page with: "NOde-Red home Automation - Select sign in method" appears but then it stuck there, regardless of the login method (google or git) I select.

The error reported is ""nora (8HlEY): socket connection error: not authorized"

  Giampaolo

**Comment by xselvasx** [comment]
When you got this error probably you need to wait 24h and all the component will reconnect automatically.
Sometime from google home device is not possible to manage nora device with message ( impossible to connect to nora); this is caused by the high number of requests from all users.
The developer is working on a new version that will be firebase based and should be able handle the load.
Thanks in advance to the developer Andrei Tatar

**Comment by ChutneyMary** [comment]
Yes, I'm experiencing a similar error logging into NORA. I'm going around in circles trying to log in.

I removed NORA from my Google Home account (this normally fixes things when it's added back in). Now I can't add NORA back into my account. Hope @andrei-tatar can find a solution. Home automation really sucks without voice.

**Comment by andrei-tatar** [comment]
Pretty much all the issues related to nora are now due to the high load (over 2000 users connected at any time) and the free heroku instance can't handle this kind of load.

I'm working on a new version that will be firebase based and should be able handle the load...

**Comment by iw2lsi** [comment]
Hi all,

  thanks for the information provided... and thanks andrei for the great job.

      Giampaolo
