### ISSUE TITLE
Stopped working when updated to v0.0.12

### ISSUE THREAD

**Issue by Paul-Reed** [andrei-tatar/node-red-contrib-nora#2]
Last night the nodes were working fine, but after updating to v0.0.12 tonight, they no longer work.
I issue the command to Google Home, and get the correct reply "turning on your table lamp".
But the output from the node just returns a blank object.

![node](https://user-images.githubusercontent.com/973580/49461636-07342300-f7ec-11e8-8963-4cb362bdee74.PNG)

The node looks as though it's connected to the server ok.

![result](https://user-images.githubusercontent.com/973580/49461693-39de1b80-f7ec-11e8-8c20-4d039420becc.PNG)

...and the node-RED log shows;

```
4 Dec 17:45:14 - [info] nora (CU3KE): connected
4 Dec 17:45:15 - [info] nora: sync 2 devices
```
There are no errors reported in the log

**Comment by andrei-tatar** [comment]
@Paul-Reed It might be an issue caused by the newly added on/off payload that weren't there in the old node version. However I did update the code to consider that. Can you please post the configuration of the node? Something like this should work fine:
![image](https://user-images.githubusercontent.com/6473183/49507589-71e76c00-f889-11e8-8c03-8377e2d0dcf2.png)

**Comment by Paul-Reed** [comment]
Hi Andrei, yes it was the changes which you introduced regards on/off.

![onoff](https://user-images.githubusercontent.com/973580/49508892-d26fac80-f87b-11e8-9365-93aa2a92906e.PNG)

The payload settings were not visible as I was allowing the brightness control, but disabling that enabled me to add boolean true/false.
I also then had to make changes to my flow to pick up the state from the payload, instead of payload.on

All back working now, thanks.
